### ISSUE TITLE
[question] runnable을 구현해서 사용해보신 경험 있으신가요?

### ISSUE THREAD

**Issue by JisuPark-dev** [adv-study/adv1#3]
저는 아직 회사에서 멀티스레드를 사용해보지 않았는데, 직접 프로젝트에서 사용해보신 경험 있으시면 어떤 경우에 왜 사용하셨는지 궁금합니다!

**Comment by youngreal** [comment]
저도 직접적으로 사용해본적은 없고 @Scheduled 사용했을때 내부에서 task를 만들때 Runnable 사용했던걸 본적이 있고, @Async에는 Callable로 task를 만들었던 기억이 있습니다. 간접적으로 어떻게 쓰이고있는지 확인해본적은 있어요
