### ISSUE TITLE
[info] Runnable 개념

### ISSUE THREAD

**Issue by JisuPark-dev** [adv-study/adv1#4]
### - Runnable은 뭔가요?
Runnable은 멀티스레드와 직접적인 연관이 있는 것은 아닙니다. 단순히 실행할 수 있는 작업(Task)을 정의하기 위한 인터페이스입니다.

### - Runnable과 Callable 비교
Runnable vs Callable 비교
특징:	Runnable,	Callable
반환값	없음 (void),	반환값 있음 (T)
예외 처리:	Checked 예외 던질 수 없음,	Checked 예외를 던질 수 있음
메서드 이름:	run(),	call()
사용 예시:	단순 작업 수행,	결과가 필요한 작업 수행

### - Runnable을 사용하는 예시
1. 체크 예외(Checked Exception) 처리 피하기

**Runnable**은 체크 예외를 던질 수 없기 때문에, 내부에서 발생하는 예외를 직접 처리해야 합니다.
따라서 **"예외를 외부로 전파하지 않고 내부에서 소멸"**시키는 용도로 사용할 수 있습니다.

```java
public static void doJobIgnoringException(Runnable job, String jobName) {
        try {
            job.run();
        } catch (Exception e) {
            log.error(jobName, e);
        }
    }

doJobIgnoringException(() -> {
		//예외없이 실행시키고 싶은 로직.
        }, "예외없이 실행시킬 로직");
```

2. 반환값이 필요 없는 작업을 단순히 실행

예를 들어, 로그 출력, 알림 전송, 데이터 저장과 같은 부가 작업에 적합합니다.
결과를 기다릴 필요가 없을 때 Runnable이 유용합니다.

### - 자바 초기에 Runnable과 Thread 조합으로 쓰다가 Executor 패턴으로 넘어간 거야?
Java 초기에는 Thread 클래스와 Runnable 인터페이스를 직접 사용해 멀티스레드 프로그램을 구현했습니다. 하지만 이런 방식은 코드의 복잡성과 비효율적인 스레드 관리를 초래할 수 있었습니다. 이를 해결하기 위해 Executor 패턴이 도입되었습니다.
문제점:
비효율적인 스레드 관리:

매번 새로운 스레드를 생성해야 하므로 많은 리소스를 소모합니다.
대량의 작업이 있을 경우 스레드 생성과 종료의 오버헤드가 발생합니다.
스레드 수 관리 어려움:

개발자가 직접 스레드 수를 제어해야 하므로, 잘못된 설계가 성능 저하를 초래할 수 있습니다.
과도한 스레드 생성으로 인해 CPU와 메모리가 부족해질 수 있습니다.
예외 처리 문제:

스레드 내부에서 발생한 예외를 메인 스레드에서 감지할 수 없습니다.

#### 전환: Executor 패턴 도입
Java 5에서 java.util.concurrent 패키지가 도입되면서, **ExecutorService**와 같은 스레드 풀 관리 도구가 제공되었습니다. 이를 통해 스레드 생성과 관리를 더 효율적으로 수행할 수 있습니다.

Executor 패턴의 장점:
스레드 풀 관리:

**ThreadPool**을 사용하여 스레드를 미리 생성하고 재사용합니다.
스레드가 많아지더라도 제한된 수의 스레드로 작업을 관리합니다.
작업 큐 지원:

새로운 작업이 들어오면 대기열에 추가하고, 사용 가능한 스레드가 있으면 자동으로 실행합니다.
예외 처리 간편화:

ExecutorService는 예외가 발생한 작업을 추적할 수 있도록 도와줍니다.
반환값 지원:

Callable 인터페이스를 통해 반환값이 있는 작업을 비동기적으로 처리할 수 있습니다.

```java
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class ExecutorExample {
    public static void main(String[] args) {
        // 스레드 풀 생성 (3개의 스레드 사용)
        ExecutorService executor = Executors.newFixedThreadPool(3);

        // 5개의 작업 제출
        for (int i = 1; i <= 5; i++) {
            final int taskNumber = i;
            executor.submit(() -> {
                System.out.println("Task " + taskNumber + " running in: " + Thread.currentThread().getName());
            });
        }

        // 스레드 풀 종료
        executor.shutdown();
    }
}
```

Thread + Runnable 방식에서 Executor 패턴으로 전환된 이유
리소스 효율성:

스레드를 매번 생성하고 파괴하는 대신, 스레드를 재사용합니다.
스레드 수 제어:

스레드 풀의 크기를 조절해 시스템 리소스의 과부하를 방지합니다.
코드 간결성:

스레드 풀을 사용하면 개발자는 작업의 생성과 실행만 신경 쓰면 됩니다. 스레드 관리 코드를 최소화할 수 있습니다.
비동기 작업의 결과 관리:

Callable 인터페이스와 **Future**를 사용하면 작업의 결과와 예외를 쉽게 추적할 수 있습니다.

#### 정리
Java 초기에는 **Thread와 Runnable**을 조합하여 멀티스레드를 구현했습니다. 하지만 이 방식은 스레드 관리가 복잡하고, 성능 문제가 발생하기 쉬웠습니다. 이러한 문제를 해결하기 위해 Java 5부터 Executor 패턴이 도입되었고, **ExecutorService**를 사용해 더 효율적이고 간단한 멀티스레드 프로그래밍이 가능해졌습니다.

따라서 현재는 Thread와 Runnable 조합보다는 Executor 패턴을 사용하는 것이 권장됩니다.

**Comment by youngreal** [comment]
강의 뒤편에서도 한번더 다룰 내용인것같네요ㅎㅎ
